// <auto-generated />
using System;
using Kutuphane.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kutuphane.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260307195458_Kutuphane")]
    partial class Kutuphane
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Kitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yayinevi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KitapId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KitapTur", b =>
                {
                    b.Property<int>("TurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TurId");

                    b.ToTable("KitapTurlari");
                });

            modelBuilder.Entity("OduncKitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlinmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GetirilmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GetirilmesiIstenenTarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OduncKitaplar");
                });

            modelBuilder.Entity("Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciSoyAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Sinifi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelNo")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciId");

                    b.ToTable("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
